export const ADD_RECEPCIONISTA = 'ADD_RECEPCIONISTA';
export const ADD_RECEPCIONISTA_SUCCESS = 'ADD_RECEPCIONISTA_SUCCESS';
export const ADD_RECEPCIONISTA_ERROR = 'ADD_RECEPCIONISTA_ERROR';

export const EDIT_RECEPCIONISTA = 'EDIT_RECEPCIONISTA';
export const EDIT_RECEPCIONISTA_SUCCESS = 'EDIT_RECEPCIONISTA_SUCCESS';
export const EDIT_RECEPCIONISTA_ERROR = 'EDIT_RECEPCIONISTA_ERROR';

export const DELETE_RECEPCIONISTA = 'DELETE_RECEPCIONISTA';
export const DELETE_RECEPCIONISTA_SUCCESS = 'DELETE_RECEPCIONISTA_SUCCESS';
export const DELETE_RECEPCIONISTA_ERROR = 'DELETE_RECEPCIONISTA_ERROR';

export const GET_RECEPCIONISTA = 'GET_RECEPCIONISTA';
export const GET_RECEPCIONISTA_SUCCESS = 'GET_RECEPCIONISTA_SUCCESS';
export const GET_RECEPCIONISTA_ERROR = 'GET_RECEPCIONISTA_ERROR';



export const SET_RECEPCIONISTA = 'SET_RECEPCIONISTA';