export const ADD_RESERVAS = 'ADD_RESERVAS';
export const ADD_RESERVAS_SUCCESS = 'ADD_RESERVAS_SUCCESS';
export const ADD_RESERVAS_ERROR = 'ADD_RESERVAS_ERROR';

export const EDIT_RESERVAS = 'EDIT_RESERVAS';
export const EDIT_RESERVAS_SUCCESS = 'EDIT_RESERVAS_SUCCESS';
export const EDIT_RESERVAS_ERROR = 'EDIT_RESERVAS_ERROR';

export const DELETE_RESERVAS = 'DELETE_RESERVAS';
export const DELETE_RESERVAS_SUCCESS = 'DELETE_RESERVAS_SUCCESS';
export const DELETE_RESERVAS_ERROR = 'DELETE_RESERVAS_ERROR';

export const GET_RESERVAS = 'GET_RESERVAS';
export const GET_RESERVAS_SUCCESS = 'GET_RESERVAS_SUCCESS';
export const GET_RESERVAS_ERROR = 'GET_RESERVAS_ERROR';


export const SET_RESERVAS = 'SET_RESERVAS';